### ISSUE TITLE
Cannot fetch new refresh token

### ISSUE THREAD

**Issue by sh123-987** [eBay/ebay-oauth-java-client#44]
Hi,

I haven't updated any of the dependencies and been using the same one. But all of a sudden the code keeps blowing up when running executing:
`OAuth2Api.getAccessToken(Environment.PRODUCTION, refreshToken, scopes);`

With this error:
`{"error":"invalid_grant","error_description":"the provided authorization refresh token is invalid or was issued to another client"}`

The refresh token I have supplied is URL encoded e.g.
`<redacted>`

Generating the refresh token from the authentication code works fine:
`OAuth2Api.exchangeCodeForAccessToken(Environment.PRODUCTION, authCode);`

**Comment by sengopal** [comment]
@sh123-987 Please refrain from publishing raw tokens in comments. This seems to be an issue with the compatibility between the consumerid in the Authorization header and consumer_id in the refresh_token. Would recommend reaching out to developer portal developer.ebay.com. Please use stackoverflow for such discussions.
