### ISSUE TITLE
example on how to make a request

### ISSUE THREAD

**Issue by AhmedX6** [eBay/ebay-oauth-java-client#46]
Hello,

Please could you show us how to get the token and an example of a request with token in the readme ?

Thanks for help

**Comment by sengopal** [comment]
The documentation is available at https://developer.ebay.com/api-docs/static/oauth-client-credentials-grant.html and https://developer.ebay.com/api-docs/static/oauth-client-credentials-grant.html.

https://github.com/eBay/ebay-oauth-java-client/blob/master/src/test/java/com/ebay/api/client/auth/oauth2/ClientCredentialsTest.java and https://github.com/eBay/ebay-oauth-java-client/blob/master/src/test/java/com/ebay/api/client/auth/oauth2/AuthorizationCodeTest.java have the code snippets on how to use the library.
