### ISSUE TITLE
SnakeYaml 2.2 is not compatible with ebay-oauth-java-client

### ISSUE THREAD

**Issue by stiwari99** [eBay/ebay-oauth-java-client#53]
We recently upgraded to spring 3.2 which uses snakeyaml 2.2 and getting following error

```
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
	at com.ebay.api.client.auth.oauth2.CredentialUtil.load(CredentialUtil.java:95) ~[ebay-oauth-java-client-1.1.7.jar:na]

```

**Comment by pup2093** [comment]
> We recently upgraded to spring 3.2 which uses snakeyaml 2.2 and getting following error
> 
> ```
> Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
> 	at com.ebay.api.client.auth.oauth2.CredentialUtil.load(CredentialUtil.java:95) ~[ebay-oauth-java-client-1.1.7.jar:na]
> ```

Same here. I tried downgrading snakeyaml to version 1.32 but then my spring boot app failed to run

**Comment by LokeshRishi** [comment]
@stiwari99 @pup2093 To resolve the `NoSuchMethodError` you're encountering, please upgrade the `ebay-oauth-java-client` library to version `1.1.10-RELEASE`. This version includes the necessary upgrade to `snakeyaml` 2.0.
